apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs
  template:
    metadata:
      name: nfs-server
      labels:
        role: nfs
    spec:
      volumes:
        - name: nfs-pv-storage
          persistentVolumeClaim:
            claimName: nfs-pvc
      securityContext:
        fsGroup: 1000
      containers:
        - name: nfs-server-container
          image: armdocker.rnd.ericsson.se/proj-am/custom/alpine-nfs
          ports:
          - containerPort: 2049
          securityContext:
            privileged: true
          env:
            - name: SHARED_DIRECTORY
              value: "/exports"
          volumeMounts:
            - mountPath: "/exports"
              name: nfs-pv-storage
