apiVersion: v1
kind: Service
metadata:
  name: nfs-lb
spec:
  type: LoadBalancer
  selector:
    role: nfs
  ports:
    - name: tcp-2049
      targetPort: 2049
      port: 2049
      protocol: TCP
  loadBalancerIP:
  allocateLoadBalancerNodePorts: false
