apiVersion: v1
kind: Service
metadata:
  name: nfs-nodeport
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    role: nfs
  ports:
    - name: tcp-2049
      targetPort: 2049
      port: 2049
      protocol: TCP
  type: NodePort
