{
 "title": "Cluster Metrics",
 "description": "Monitors all persistent volumes that exists within a Kubernetes cluster. Prometheus is used as datasource. ",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "warning_threshold", "label": "PVC % Used Warning Threshold", "query": "80" },
   { "name": "kubelet_service", "label": "Kubelet Source", "query": { "query": "label_values(service)" } },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "EO Dimensioning",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "All Containers Total - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"${namespace}\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"memory\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"memory\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "All Containers Total - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "yaxes": [
    { "format": "core" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"cpu\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"cpu\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "All Pods Max - Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "max(rate(container_network_receive_bytes_total{namespace=\"${namespace}\", interface=\"eth0\"}[1m]))",
     "legendFormat": "Received Bytes"
    },
    {
     "expr": "max(rate(container_network_transmit_bytes_total{namespace=\"${namespace}\", interface=\"eth0\"}[1m]))",
     "legendFormat": "Transmitted Bytes"
    }
   ]
  },
  {
   "title": "All Pods Max - Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "max(rate(container_fs_reads_total{namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "Reads Bytes"
    },
    {
     "expr": "max(rate(container_fs_writes_total{namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "Writes Bytes"
    }
   ]
  },
  {
   "title": "All Pods Max - Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "max(rate(container_fs_reads_bytes_total{namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "Reads Bytes"
    },
    {
     "expr": "max(rate(container_fs_writes_bytes_total{namespace=\"${namespace}\"}[1m]))",
     "legendFormat": "Writes Bytes"
    }
   ]
  },
  {
   "title": "All PVC Total - Disk space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace=\"${namespace}\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{namespace=\"${namespace}\"})",
     "legendFormat": "Space"
    }
   ]
  },
  {
   "title": "All Containers Total - Ephemeral Storage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_fs_reads_bytes_total{namespace=\"$namespace\"})",
     "legendFormat": "Reads Bytes"
    },
    {
     "expr": "avg(container_fs_writes_bytes_total{namespace=\"$namespace\"})",
     "legendFormat": "Writes Bytes"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"ephemeral_storage\", unit=\"byte\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"ephemeral_storage\", unit=\"byte\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes - Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_memory_Active_bytes{}) by (instance)",
       "legendFormat": "Node {{instance}}"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{}) by (instance)",
       "legendFormat": "Node {{instance}}"
      }
     ]
    },
    {
     "title": "Nodes - CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "core" } },
     "yaxes": [
      { "format": "core" }
     ],
     "targets": [
      { "expr": "instance:node_cpu:rate:sum{}", "legendFormat": "Node {{instance}}" }
     ]
    },
    {
     "title": "Nodes - Network I/O",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "instance:node_network_receive_bytes:rate:sum{}",
       "legendFormat": "Node {{instance}}"
      }
     ]
    },
    {
     "title": "Nodes - PVC",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PVC alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "PVCs Full in 2 days - Based on Daily Usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(\n  count (\n    (kubelet_volume_stats_available_bytes{namespace=~\"${namespace}\"})\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{namespace=~\"${namespace}\"}[1d], 2 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
      }
     ]
    },
    {
     "title": "PVCs Full in 5 days - Based on Daily Usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(\n  count (\n    (kubelet_volume_stats_available_bytes{namespace=~\"${namespace}\"})\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{namespace=~\"${namespace}\"}[1d], 5 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
      }
     ]
    },
    {
     "title": "PVCs Full in 1 Week - Based on Daily Usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(\n  count (\n    (kubelet_volume_stats_available_bytes{namespace=~\"${namespace}\"})\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{namespace=~\"${namespace}\"}[1d], 7 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
      }
     ]
    },
    {
     "title": "PVCs Above Warning Threshold",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{namespace=~\"${namespace}\"} ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{namespace=~\"${namespace}\"} )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{namespace=~\"${namespace}\"} )) >= (${warning_threshold} / 100)) or vector (0)"
      }
     ]
    },
    {
     "title": "PVCs in Pending State",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count((kube_persistentvolumeclaim_status_phase{namespace=~\"${namespace}\",phase=\"Pending\"}==1)) or vector(0)"
      }
     ]
    },
    {
     "title": "PVCs in Lost State",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count((kube_persistentvolumeclaim_status_phase{namespace=~\"${namespace}\",phase=\"Lost\"}==1)) or vector(0)"
      }
     ]
    }
   ]
  },
  {
   "title": "PVC graphical usage data ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Running PVCs Used Bytes",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{namespace=~\"${namespace}\"}))",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PVC usage statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Persistent Volume Claim",
     "type": "table",
     "gridPos": { "h": 26, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": " sum by (persistentvolumeclaim,namespace,storageclass,volumename) (kube_persistentvolumeclaim_info{namespace=~\"${namespace}\"})"
      },
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=~\"${namespace}\"})"
      },
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"${namespace}\"})"
      },
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes{namespace=~\"${namespace}\"})"
      },
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{namespace=~\"${namespace}\",phase=~\"(Pending|Lost)\"}) by (persistentvolumeclaim) + sum(kube_persistentvolumeclaim_status_phase{namespace=~\"${namespace}\",phase=~\"(Lost)\"}) by (persistentvolumeclaim)"
      },
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"${namespace}\"}/kubelet_volume_stats_capacity_bytes{namespace=~\"${namespace}\"} * 100)"
      }
     ]
    }
   ]
  },
  {
   "title": "PVC usage Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hourly Volume Usage Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes{namespace=\"${namespace}\", service=\"${kubelet_service}\"}[1h])",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Daily Volume Usage Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes{namespace=~\"${namespace}\", service=\"${kubelet_service}\"}[1d])",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Weekly Volume Usage Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes{namespace=~\"${namespace}\", service=\"${kubelet_service}\"}[1w])",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node storage alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes Full in 2 days - Based on Daily Usage",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  count (\n    (node_filesystem_avail_bytes{job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})\n    and\n    (predict_linear(node_filesystem_avail_bytes{job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}[1d], 2 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
      }
     ]
    },
    {
     "title": "Nodes Full in 7 days - Based on Daily Usage",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  count (\n    (node_filesystem_avail_bytes{job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})\n    and\n    (predict_linear(node_filesystem_avail_bytes{job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}[1d], 7 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
      }
     ]
    },
    {
     "title": "Nodes Full in 31 days - Based on Daily Usage",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  count (\n    (node_filesystem_avail_bytes{job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})\n    and\n    (predict_linear(node_filesystem_avail_bytes{job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}[1d], 31 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
      }
     ]
    }
   ]
  },
  {
   "title": "Node storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Storage - Total",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_filesystem_size_bytes{job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
      }
     ]
    },
    {
     "title": "Node Storage - Usage",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 19, "x": 5, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Node Memory Usage Overview",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (instance) (node_filesystem_size_bytes{job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum by (instance) (node_filesystem_avail_bytes{job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
      },
      {
       "expr": "sum by (instance) (node_filesystem_size_bytes{job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} - node_filesystem_avail_bytes{job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
      },
      {
       "expr": "sum by (instance) (100 - ((node_filesystem_avail_bytes{job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}))"
      }
     ]
    },
    {
     "title": "Node Storage - Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ephemeral storage graphical usage data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Ephemeral Storage Used Bytes",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (container_fs_reads_bytes_total{namespace=\"$namespace\", container!=\"\"})",
       "legendFormat": "Reads {{pod}}"
      },
      {
       "expr": "sum by (pod) (container_fs_writes_bytes_total{namespace=\"$namespace\", container!=\"\"})",
       "legendFormat": "Writes {{pod}}"
      },
      {
       "expr": "sum by (pod) (kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"ephemeral_storage\"})",
       "legendFormat": "Limits {{pod}}"
      },
      {
       "expr": "sum by (pod) (kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"ephemeral_storage\"})",
       "legendFormat": "Requests {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}