{
 "title": "CVNFM - RED Metrics All",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "SOURCE", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Application Manager PG DB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections pools",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{app=\"application-manager-postgres\", datname=\"orchestrator\"})",
       "legendFormat": "Orchestrator"
      },
      {
       "expr": "sum(pg_stat_activity_count{app=\"application-manager-postgres\", datname=\"onboarding\"})",
       "legendFormat": "Onboarding"
      },
      {
       "expr": "sum(pg_stat_activity_count{app=\"application-manager-postgres\", datname=\"camunda\"})",
       "legendFormat": "Camunda"
      },
      {
       "expr": "sum(pg_stat_activity_count{app=\"application-manager-postgres\", datname=\"postgres\"})",
       "legendFormat": "Postgres"
      },
      {
       "expr": "sum(pg_stat_activity_count{app=\"application-manager-postgres\", datname=\"toscao\"})",
       "legendFormat": "TOSCAO"
      },
      {
       "expr": "sum(pg_stat_activity_count{app=\"application-manager-postgres\", datname=\"template0\"})",
       "legendFormat": "template0"
      },
      {
       "expr": "sum(pg_stat_activity_count{app=\"application-manager-postgres\", datname=\"template1\"})",
       "legendFormat": "template1"
      }
     ]
    }
   ]
  },
  {
   "title": "Workflow Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection Pool Usage (eric-am-common-wfs)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hikaricp_connections_active{app=\"eric-am-common-wfs\", job=\"eric-am-common-wfs\"}",
       "legendFormat": "Active connections ({{pool}})"
      },
      {
       "expr": "hikaricp_connections_active{app=\"eric-am-common-wfs\", job=\"eric-am-common-wfs\"} + hikaricp_connections_idle{app=\"eric-am-common-wfs\", job=\"eric-am-common-wfs\"}",
       "legendFormat": "All connections ({{pool}})"
      }
     ]
    },
    {
     "title": "Connection Pool Usage in seconds (eric-am-common-wfs)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_usage_seconds_sum{app=\"eric-am-common-wfs\", job=\"eric-am-common-wfs\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Average Response Latency per Second (eric-am-common-wfs)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{app=\"eric-am-common-wfs\", status!~\"5..\"}[2m]))/sum(rate(http_server_requests_seconds_count{app=\"eric-am-common-wfs\", status!~\"5..\"}[2m])) or on() vector(0)",
       "legendFormat": "HTTP-AVG"
      },
      {
       "expr": "max(http_server_requests_seconds_max{app=\"eric-am-common-wfs\", status!~\"5..\"}) or on() vector(0)",
       "legendFormat": "HTTP-MAX"
      }
     ]
    },
    {
     "title": "Request Rate per Second (eric-am-common-wfs)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"eric-am-common-wfs\", uri!=\"/actuator/health\", uri!=\"/actuator/health/**\", uri!=\"/actuator/prometheus\"}[2m])) by (uri,method) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Top 10 API's by Request Rate (eric-am-common-wfs)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_count{app=\"eric-am-common-wfs\", uri!=\"/actuator/health\", uri!=\"/actuator/health/**\", uri!=\"/actuator/prometheus\"}[2m]))) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Error Rate per Second (eric-am-common-wfs)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"eric-am-common-wfs\", status=~\"5..\", uri!=\"/actuator/health\", uri!=\"/actuator/health/**\", uri!=\"/actuator/prometheus\"}[2m])) by (uri,method) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Response time of 50%, 75%, 90%, 95%, 99% & 100% of requests (eric-am-common-wfs)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(http_server_requests_seconds_bucket{app=\"eric-am-common-wfs\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "100%"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{app=\"eric-am-common-wfs\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "99% "
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{app=\"eric-am-common-wfs\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{app=\"eric-am-common-wfs\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{app=\"eric-am-common-wfs\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{app=\"eric-am-common-wfs\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Top 10 API's by Latency (eric-am-common-wfs)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_sum{app=\"eric-am-common-wfs\", uri!=\"/actuator/health\", uri!=\"/actuator/health/**\", uri!=\"/actuator/prometheus\"}[2m]))) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "EVNFM UI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Rate per Second (eric-am-common-wfs-ui)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"eric-am-common-wfs-ui\", uri!=\"/actuator/health\", uri!=\"/actuator/prometheus\"}[2m]))by (uri,method) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Error Rate per Second (eric-am-common-wfs-ui)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"eric-am-common-wfs-ui\", status=~\"5..\", uri!=\"/actuator/health\", uri!=\"/actuator/prometheus\"}[2m])) by (uri,method) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Average Response Latency per Second (eric-am-common-wfs-ui)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{app=\"eric-am-common-wfs-ui\", status!~\"5..\"}[2m]))/sum(rate(http_server_requests_seconds_count{app=\"eric-am-common-wfs-ui\", status!~\"5..\"}[2m])) or on() vector(0)",
       "legendFormat": "HTTP-AVG"
      },
      {
       "expr": "max(http_server_requests_seconds_max{app=\"eric-am-common-wfs-ui\", status!~\"5..\"}) or on() vector(0)",
       "legendFormat": "HTTP-MAX"
      }
     ]
    },
    {
     "title": "Response time of 50%, 75%, 90%, 95%, 99% & 100% of requests (eric-am-common-wfs-ui)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(http_server_requests_seconds_bucket{app=\"eric-am-common-wfs-ui\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "100%"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{app=\"eric-am-common-wfs-ui\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "99% "
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{app=\"eric-am-common-wfs-ui\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{app=\"eric-am-common-wfs-ui\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{app=\"eric-am-common-wfs-ui\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{app=\"eric-am-common-wfs-ui\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Top 10 API's by Request Rate (eric-am-common-wfs-ui)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_count{app=\"eric-am-common-wfs-ui\", uri!=\"/actuator/health\", uri!=\"/actuator/prometheus\"}[2m]))) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Top 10 API's by Latency (eric-am-common-wfs-ui)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_sum{app=\"eric-am-common-wfs-ui\", uri!=\"/actuator/health\", uri!=\"/actuator/prometheus\"}[2m]))) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Onboarding",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Rate per Second (eric-am-onboarding-service)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"eric-am-onboarding-service\", uri!=\"/actuator/health\", uri!=\"/actuator/health/**\", uri!=\"/actuator/prometheus\"}[2m]))by (uri,method) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Error Rate per Second (eric-am-onboarding-service)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"eric-am-onboarding-service\", status=~\"5..\", uri!=\"/actuator/health\", uri!=\"/actuator/health/**\", uri!=\"/actuator/prometheus\"}[2m])) by (uri,method) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Average Response Latency per Second (eric-am-onboarding-service)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{app=\"eric-am-onboarding-service\", status!~\"5..\"}[2m]))/sum(rate(http_server_requests_seconds_count{app=\"eric-am-onboarding-service\", status!~\"5..\"}[2m])) or on() vector(0)",
       "legendFormat": "HTTP-AVG"
      },
      {
       "expr": "max(http_server_requests_seconds_max{app=\"eric-am-onboarding-service\", status!~\"5..\"}) or on() vector(0)",
       "legendFormat": "HTTP-MAX"
      }
     ]
    },
    {
     "title": "HTTP Client Requests Performance  (eric-am-onboarding-service)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_client_requests_seconds_max{app=\"eric-am-onboarding-service\", status!~\"5..\", status!~\"4..\", uri=~\".*/blobs.*\"}",
       "legendFormat": "{{app}} - {{client_name}}"
      }
     ]
    },
    {
     "title": "Top 10 API's by Request Rate (eric-am-onboarding-service)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_count{app=\"eric-am-onboarding-service\", uri!=\"/actuator/health/**\", uri!=\"/actuator/health\", uri!=\"/actuator/prometheus\"}[2m]))) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Response time of 50%, 75%, 90%, 95%, 99% & 100% of requests (eric-am-onboarding-service)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(http_server_requests_seconds_bucket{app=\"eric-am-onboarding-service\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "100%"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{app=\"eric-am-onboarding-service\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "99% "
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{app=\"eric-am-onboarding-service\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{app=\"eric-am-onboarding-service\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{app=\"eric-am-onboarding-service\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{app=\"eric-am-onboarding-service\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Top 10 API's by Latency (eric-am-onboarding-service)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_sum{app=\"eric-am-onboarding-service\", uri!=\"/actuator/health\", uri!=\"/actuator/health/**\", uri!=\"/actuator/prometheus\"}[2m]))) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Rate per Second (eric-eo-api-gateway)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"eric-eo-api-gateway\", uri!=\"/actuator/health\", uri!=\"/actuator/prometheus\"}[2m])) by (uri,method) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Error Rate per Second (eric-eo-api-gateway)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"eric-eo-api-gateway\", status=~\"5..\", uri!=\"/actuator/health\", uri!=\"/actuator/prometheus\"}[2m])) by (uri,method) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Average Response Latency per Second (eric-eo-api-gateway)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{app=\"eric-eo-api-gateway\", status!~\"5..\"}[2m]))/sum(rate(http_server_requests_seconds_count{app=\"eric-eo-api-gateway\", status!~\"5..\"}[2m])) or on() vector(0)",
       "legendFormat": "HTTP-AVG"
      },
      {
       "expr": "max(http_server_requests_seconds_max{app=\"eric-eo-api-gateway\", status!~\"5..\"}) or on() vector(0)",
       "legendFormat": "HTTP-MAX"
      }
     ]
    },
    {
     "title": "HTTP Client Requests Performance (eric-eo-api-gateway)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_client_requests_seconds_sum{app=\"eric-eo-api-gateway\", status!~\"5..\"}[2m]))/sum(rate(http_client_requests_seconds_count{app=\"eric-eo-api-gateway\", status!~\"5..\"}[2m])) or on() vector(0)",
       "legendFormat": "Average Client HTTP Request Time"
      },
      {
       "expr": "max(http_client_requests_seconds_max{app=\"eric-eo-api-gateway\", status!~\"5..\"}) or on() vector(0)",
       "legendFormat": "Maximum Client HTTP Request Time"
      }
     ]
    },
    {
     "title": "Top 10 API's by Request Rate (eric-eo-api-gateway)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_count{app=\"eric-eo-api-gateway\", uri!=\"/actuator/health\", uri!=\"/actuator/prometheus\"}[2m]))) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Response time of 50%, 75%, 90%, 95%, 99% & 100% of requests (eric-eo-api-gateway)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-api-gateway\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "100%"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-api-gateway\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "99% "
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-api-gateway\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-api-gateway\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-api-gateway\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-api-gateway\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Top 10 API's by Latency (eric-eo-api-gateway)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_sum{app=\"eric-eo-api-gateway\", uri!=\"/actuator/health\", uri!=\"/actuator/prometheus\"}[2m]))) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Crypto Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Rate per Second (eric-eo-evnfm-crypto)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"eric-eo-evnfm-crypto\", uri!=\"/actuator/health\", uri!=\"/actuator/prometheus\"}[2m])) by (uri,method) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Error Rate per Second (eric-eo-evnfm-crypto)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"eric-eo-evnfm-crypto\", status=~\"5..\", uri!=\"/actuator/health\", uri!=\"/actuator/prometheus\"}[2m])) by (uri,method) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Average Response Latency per Second (eric-eo-evnfm-crypto)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{app=\"eric-eo-evnfm-crypto\", status!~\"5..\"}[2m]))/sum(rate(http_server_requests_seconds_count{app=\"eric-eo-evnfm-crypto\", status!~\"5..\"}[2m])) or on() vector(0)",
       "legendFormat": "HTTP-AVG"
      },
      {
       "expr": "max(http_server_requests_seconds_max{app=\"eric-eo-evnfm-crypto\", status!~\"5..\"}) or on() vector(0)",
       "legendFormat": "HTTP-MAX"
      }
     ]
    },
    {
     "title": "Response time of 50%, 75%, 90%, 95%, 99% & 100% of requests (eric-eo-evnfm-crypto)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-evnfm-crypto\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "100%"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-evnfm-crypto\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "99% "
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-evnfm-crypto\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-evnfm-crypto\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-evnfm-crypto\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-evnfm-crypto\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Top 10 API's by Request Rate (eric-eo-evnfm-crypto)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_count{app=\"eric-eo-evnfm-crypto\", uri!=\"/actuator/health\", uri!=\"/actuator/prometheus\"}[2m]))) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Top 10 API's by Latency (eric-eo-evnfm-crypto)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_sum{app=\"eric-eo-evnfm-crypto\", uri!=\"/actuator/health\", uri!=\"/actuator/prometheus\"}[2m]))) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RBAC/NBI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Rate per Second (eric-eo-evnfm-nbi)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"eric-eo-evnfm-nbi\", uri!=\"/actuator/health\", uri!=\"/actuator/prometheus\"}[2m])) by (uri,method) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Error Rate per Second (eric-eo-evnfm-nbi)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"eric-eo-evnfm-nbi\", status=~\"5..\", uri!=\"/actuator/health\", uri!=\"/actuator/prometheus\"}[2m])) by (uri,method) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Average Response Latency per Second (eric-eo-evnfm-nbi)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{app=\"eric-eo-evnfm-nbi\", status!~\"5..\"}[2m]))/sum(rate(http_server_requests_seconds_count{app=\"eric-eo-evnfm-nbi\", status!~\"5..\"}[2m])) or on() vector(0)",
       "legendFormat": "HTTP-AVG"
      },
      {
       "expr": "max(http_server_requests_seconds_max{app=\"eric-eo-evnfm-nbi\", status!~\"5..\"}) or on() vector(0)",
       "legendFormat": "HTTP-MAX"
      }
     ]
    },
    {
     "title": "Response time of 50%, 75%, 90%, 95%, 99% & 100% of requests (eric-eo-evnfm-nbi)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-evnfm-nbi\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "100%"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-evnfm-nbi\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "99% "
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-evnfm-nbi\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-evnfm-nbi\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-evnfm-nbi\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-evnfm-nbi\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Top 10 API's by Request Rate (eric-eo-evnfm-nbi)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_count{app=\"eric-eo-evnfm-nbi\", uri!=\"/actuator/health\", uri!=\"/actuator/prometheus\"}[2m]))) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Top 10 API's by Latency (eric-eo-evnfm-nbi)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_sum{app=\"eric-eo-evnfm-nbi\", uri!=\"/actuator/health\", uri!=\"/actuator/prometheus\"}[2m]))) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "User Management",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Rate per Second (eric-eo-usermgmt)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"eric-eo-usermgmt\", uri!=\"/actuator/health\", uri!=\"/actuator/prometheus\"}[2m]))by (uri,method) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Error Rate per Second (eric-eo-usermgmt)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"eric-eo-usermgmt\", status=~\"5..\", uri!=\"/actuator/health\", uri!=\"/actuator/prometheus\"}[2m])) by (uri,method) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Average Response Latency per Second (eric-eo-usermgmt)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{app=\"eric-eo-usermgmt\", status!~\"5..\"}[2m]))/sum(rate(http_server_requests_seconds_count{app=\"eric-eo-usermgmt\", status!~\"5..\"}[2m])) or on() vector(0)",
       "legendFormat": "HTTP-AVG"
      },
      {
       "expr": "max(http_server_requests_seconds_max{app=\"eric-eo-usermgmt\", status!~\"5..\"}) or on() vector(0)",
       "legendFormat": "HTTP-MAX"
      }
     ]
    },
    {
     "title": "Response time of 50%, 75%, 90%, 95%, 99% & 100% of requests (eric-eo-usermgmt)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-usermgmt\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "100%"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-usermgmt\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "99% "
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-usermgmt\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-usermgmt\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-usermgmt\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{app=\"eric-eo-usermgmt\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Top 10 API's by Request Rate (eric-eo-usermgmt)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_count{app=\"eric-eo-usermgmt\", uri!=\"/actuator/health\", uri!=\"/actuator/prometheus\"}[2m]))) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Top 10 API's by Latency (eric-eo-usermgmt)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_sum{app=\"eric-eo-usermgmt\", uri!=\"/actuator/health\", uri!=\"/actuator/prometheus\"}[2m]))) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Orchestrator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection Pool Usage in seconds (eric-vnfm-orchestrator-service)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hikaricp_connections_active{app=\"eric-vnfm-orchestrator-service\", job=\"eric-vnfm-orchestrator-service\"}",
       "legendFormat": "Active connections ({{instance}})"
      },
      {
       "expr": "hikaricp_connections_active{app=\"eric-vnfm-orchestrator-service\", job=\"eric-vnfm-orchestrator-service\"} + hikaricp_connections_idle{app=\"eric-vnfm-orchestrator-service\", job=\"eric-vnfm-orchestrator-service\"}",
       "legendFormat": "All connections ({{instance}})"
      }
     ]
    },
    {
     "title": "Connection Pool Usage (eric-vnfm-orchestrator-service)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "hikaricp_connections_usage_seconds_max{app=\"eric-vnfm-orchestrator-service\", job=\"eric-vnfm-orchestrator-service\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Request Rate per Second (eric-vnfm-orchestrator-service)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"eric-vnfm-orchestrator-service\", uri!=\"/actuator/health/**\", uri!=\"/actuator/prometheus\"}[2m]))by (uri,method) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Error Rate per Second (eric-vnfm-orchestrator-service)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"eric-vnfm-orchestrator-service\", status=~\"5..\", uri!=\"/actuator/health\", uri!=\"/actuator/prometheus\"}[2m])) by (uri,method) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Average Response Latency per Second (eric-vnfm-orchestrator-service)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{app=\"eric-vnfm-orchestrator-service\", status!~\"5..\"}[2m]))/sum(rate(http_server_requests_seconds_count{app=\"eric-vnfm-orchestrator-service\", status!~\"5..\"}[2m])) or on() vector(0)",
       "legendFormat": "HTTP-AVG"
      },
      {
       "expr": "max(http_server_requests_seconds_max{app=\"eric-vnfm-orchestrator-service\", status!~\"5..\"}) or on() vector(0)",
       "legendFormat": "HTTP-MAX"
      }
     ]
    },
    {
     "title": "Response time of 50%, 75%, 90%, 95%, 99% & 100% of requests (eric-vnfm-orchestrator-service)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(http_server_requests_seconds_bucket{app=\"eric-vnfm-orchestrator-service\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "100%"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{app=\"eric-vnfm-orchestrator-service\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "99% "
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{app=\"eric-vnfm-orchestrator-service\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{app=\"eric-vnfm-orchestrator-service\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{app=\"eric-vnfm-orchestrator-service\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{app=\"eric-vnfm-orchestrator-service\"}[2m])) by (le)) or on() vector(0)",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Top 10 API's by Request Rate (eric-vnfm-orchestrator-service)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_count{app=\"eric-vnfm-orchestrator-service\", uri!=\"/actuator/health/**\", uri!=\"/actuator/prometheus\"}[2m]))) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Top 10 API's by Latency (eric-vnfm-orchestrator-service)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(10, sum by(uri, method) (rate(http_server_requests_seconds_sum{app=\"eric-vnfm-orchestrator-service\", uri!=\"/actuator/health/**\", uri!=\"/actuator/prometheus\"}[2m]))) or on() vector(0)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "HTTP Client Requests Performance (eric-vnfm-orchestrator-service)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_client_requests_seconds_max{app=\"eric-vnfm-orchestrator-service\", status!~\"5..\", status!~\"4..\", client_name=~\"eric-am-onboarding-service.*\"}",
       "legendFormat": "{{app}} - {{client_name}}"
      }
     ]
    },
    {
     "title": "HTTP Client Requests Performance (eric-vnfm-orchestrator-service)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_client_requests_seconds_max{app=\"eric-vnfm-orchestrator-service\", status!~\"5..\", status!~\"4..\", client_name=~\"eric-am-common-wfs.*\"}",
       "legendFormat": "{{app}} - {{client_name}}"
      }
     ]
    },
    {
     "title": "HTTP Client Requests Performance (eric-vnfm-orchestrator-service)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_client_requests_seconds_max{app=\"eric-vnfm-orchestrator-service\", status!~\"5..\", status!~\"4..\", client_name=~\"eric-eo-evnfm-crypto.*\"}",
       "legendFormat": "{{app}} - {{client_name}}"
      }
     ]
    }
   ]
  }
 ]
}