{
 "title": "CVNFM - Containers Metrics",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "eric_am_common_wfs_ui",
    "query": {
     "query": "kube_pod_container_info{namespace=\"${namespace}\", container=~\"eric-am-common-wfs-ui.*\"}"
    }
   },
   {
    "name": "eric_vnfm_orchestrator_service",
    "query": {
     "query": "kube_pod_container_info{namespace=\"${namespace}\", container=~\"eric-vnfm-orchestrator-service.*\"}"
    }
   },
   {
    "name": "eric_am_common_wfs",
    "query": {
     "query": "kube_pod_container_info{namespace=\"${namespace}\", pod=~\"eric-am-common-wfs-[^-]*-*[^-]*\"}"
    }
   },
   {
    "name": "eric_am_onboarding_service",
    "query": {
     "query": "kube_pod_container_info{namespace=\"${namespace}\", container=~\"eric-am-onboarding-service.*\"}"
    }
   },
   { "name": "datasource", "label": "SOURCE", "query": "prometheus" },
   {
    "name": "app_mng_postgres",
    "query": {
     "query": "kube_pod_container_info{namespace=\"${namespace}\", pod=~\"^application-manager-postgres-\\\\d{1}$\"}"
    }
   },
   {
    "name": "eric_eo_evnfm_crypto",
    "query": {
     "query": "kube_pod_container_info{namespace=\"${namespace}\", container=~\"eric-eo-evnfm-crypto.*\"}"
    }
   },
   {
    "name": "eric_eo_evnfm_nbi",
    "query": {
     "query": "kube_pod_container_info{namespace=\"${namespace}\", container=~\"eric-eo-evnfm-nbi.*\"}"
    }
   },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pg_data_app_mng_postgres",
    "query": {
     "query": "kubelet_volume_stats_used_bytes{namespace=\"${namespace}\",  persistentvolumeclaim=~\"pg-data-application-manager-postgres.*\"}"
    }
   },
   { "name": "kubelet_service", "label": "Kubelet Source", "query": { "query": "label_values(service)" } },
   {
    "name": "eric_eo_batch_manager",
    "query": {
     "query": "kube_pod_container_info{namespace=\"${namespace}\", pod=~\"eric-eo-batch-manager-[^-]*-*[^-]*\"}"
    }
   },
   {
    "name": "eric_vnfm_ip_orchestrator_service",
    "query": {
     "query": "cvnfm_enm_running_metrics_total{kubernetes_namespace=\"${namespace}\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Application Manager PG DB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "application-manager-postgres (application-manager-postgres-${app_mng_postgres}) - Memory",
     "type": "graph",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 1 },
     "repeat": "app_mng_postgres",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{namespace=\"${namespace}\", container=\"application-manager-postgres\", pod=~\"application-manager-postgres-${app_mng_postgres}\"})",
       "legendFormat": "Working set (all touched pages)"
      },
      {
       "expr": "container_memory_rss{namespace=\"${namespace}\", pod=~\"application-manager-postgres-${app_mng_postgres}\", container=\"application-manager-postgres\", service=\"${kubelet_service}\"}",
       "legendFormat": "Rss (size of memory used by a container's working set)"
      },
      {
       "expr": "max(container_memory_usage_bytes{namespace=\"${namespace}\", pod=~\"application-manager-postgres-${app_mng_postgres}\", container=\"application-manager-postgres\", service=\"${kubelet_service}\"})",
       "legendFormat": "Usage (all memory usage)"
      },
      {
       "expr": "max(container_memory_max_usage_bytes{namespace=\"${namespace}\", pod=~\"application-manager-postgres-${app_mng_postgres}\", container=\"application-manager-postgres\", service=\"${kubelet_service}\"})",
       "legendFormat": "Max Usage (maximum memory usage recorded)"
      },
      {
       "expr": "max(container_memory_cache{namespace=\"${namespace}\", pod=~\"application-manager-postgres-${app_mng_postgres}\", container=\"application-manager-postgres\", service=\"${kubelet_service}\"})",
       "legendFormat": "Cache (container's page cache)"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"memory\", container=\"application-manager-postgres\", pod=~\"application-manager-postgres-${app_mng_postgres}\"})",
       "legendFormat": "Requested"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"memory\", container=\"application-manager-postgres\", pod=~\"application-manager-postgres-${app_mng_postgres}\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "application-manager-postgres (application-manager-postgres-${app_mng_postgres}) - CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "repeat": "app_mng_postgres",
     "fieldConfig": { "defaults": { "unit": "core" } },
     "yaxes": [
      { "format": "core" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\", container=\"application-manager-postgres\", pod=\"application-manager-postgres-${app_mng_postgres}\", service=\"${kubelet_service}\"}[1m]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"cpu\", container=\"application-manager-postgres\", pod=\"application-manager-postgres-${app_mng_postgres}\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"cpu\", container=\"application-manager-postgres\", pod=\"application-manager-postgres-${app_mng_postgres}\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "application-manager-postgres-metrics (application-manager-postgres-${app_mng_postgres}) - Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
     "repeat": "app_mng_postgres",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{namespace=\"${namespace}\", container=\"application-manager-postgres-metrics\", pod=\"application-manager-postgres-${app_mng_postgres}\", service=\"${kubelet_service}\"})",
       "legendFormat": "Usage"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"memory\", container=\"application-manager-postgres-metrics\", pod=\"application-manager-postgres-${app_mng_postgres}\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"memory\", container=\"application-manager-postgres-metrics\", pod=\"application-manager-postgres-${app_mng_postgres}\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "application-manager-postgres-metrics (application-manager-postgres-${app_mng_postgres}) - CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
     "repeat": "app_mng_postgres",
     "fieldConfig": { "defaults": { "unit": "core" } },
     "yaxes": [
      { "format": "core" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\", container=\"application-manager-postgres-metrics\", pod=\"application-manager-postgres-${app_mng_postgres}\", service=\"${kubelet_service}\"}[1m]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"cpu\", container=\"application-manager-postgres-metrics\", pod=\"application-manager-postgres-${app_mng_postgres}\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"cpu\", container=\"application-manager-postgres-metrics\", pod=\"application-manager-postgres-${app_mng_postgres}\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "application-manager-postgres-${app_mng_postgres} - Network I/O",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
     "repeat": "app_mng_postgres",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"${namespace}\", pod=\"application-manager-postgres-${app_mng_postgres}\", interface=\"eth0\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Received Bytes"
      },
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"${namespace}\", pod=\"application-manager-postgres-${app_mng_postgres}\", interface=\"eth0\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Transmitted Bytes"
      }
     ]
    },
    {
     "title": "application-manager-postgres (application-manager-postgres-${app_mng_postgres}) - Disk IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
     "repeat": "app_mng_postgres",
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_reads_total{namespace=\"${namespace}\", container=\"application-manager-postgres\", pod=~\"application-manager-postgres-${app_mng_postgres}\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Reads {{device}}"
      },
      {
       "expr": "rate(container_fs_writes_total{namespace=\"${namespace}\", container=\"application-manager-postgres\", pod=~\"application-manager-postgres-${app_mng_postgres}\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Writes {{device}}"
      }
     ]
    },
    {
     "title": "application-manager-postgres (application-manager-postgres-${app_mng_postgres}) - Disk Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
     "repeat": "app_mng_postgres",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_reads_bytes_total{namespace=\"${namespace}\", container=\"application-manager-postgres\", pod=~\"application-manager-postgres-${app_mng_postgres}\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Reads {{device}}"
      },
      {
       "expr": "rate(container_fs_writes_bytes_total{namespace=\"${namespace}\", container=\"application-manager-postgres\", pod=~\"application-manager-postgres-${app_mng_postgres}\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Writes {{device}}"
      }
     ]
    },
    {
     "title": "application-manager-postgres-metrics (application-manager-postgres-${app_mng_postgres}) - Disk IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
     "repeat": "app_mng_postgres",
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_reads_total{namespace=\"${namespace}\", container=\"application-manager-postgres-metrics\", pod=~\"application-manager-postgres-${app_mng_postgres}\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Reads {{device}}"
      },
      {
       "expr": "rate(container_fs_writes_total{namespace=\"${namespace}\", container=\"application-manager-postgres-metrics\", pod=~\"application-manager-postgres-${app_mng_postgres}\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Writes {{device}}"
      }
     ]
    },
    {
     "title": "application-manager-postgres-metrics (application-manager-postgres-${app_mng_postgres}) - Disk Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
     "repeat": "app_mng_postgres",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_reads_bytes_total{namespace=\"${namespace}\", container=\"application-manager-postgres-metrics\", pod=~\"application-manager-postgres-${app_mng_postgres}\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Reads {{device}}"
      },
      {
       "expr": "rate(container_fs_writes_bytes_total{namespace=\"${namespace}\", container=\"application-manager-postgres-metrics\", pod=~\"application-manager-postgres-${app_mng_postgres}\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Writes {{device}}"
      }
     ]
    },
    {
     "title": "application-manager-postgres-${app_mng_postgres} - Processes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 90 },
     "repeat": "app_mng_postgres",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "container_processes{namespace=\"$namespace\", container=\"application-manager-postgres\", pod=~\"application-manager-postgres-${app_mng_postgres}\"}",
       "legendFormat": "{{container}} count"
      },
      {
       "expr": "container_processes{namespace=\"$namespace\", container=\"application-manager-postgres-metrics\", pod=~\"application-manager-postgres-${app_mng_postgres}\"}",
       "legendFormat": "{{container}} count"
      },
      {
       "expr": "container_processes{namespace=\"$namespace\", container=\"logshipper\", pod=~\"application-manager-postgres-${app_mng_postgres}\"}",
       "legendFormat": "{{container}} count"
      }
     ]
    },
    {
     "title": "pg-data-application-manager-postgres-${pg_data_app_mng_postgres} - PVC",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 99 },
     "repeat": "pg_data_app_mng_postgres",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{namespace=\"${namespace}\", persistentvolumeclaim=~\"pg-data-application-manager-postgres-${pg_data_app_mng_postgres}\"}",
       "legendFormat": "Usage"
      },
      {
       "expr": "kubelet_volume_stats_capacity_bytes{namespace=\"${namespace}\", persistentvolumeclaim=~\"pg-data-application-manager-postgres-${pg_data_app_mng_postgres}\"}",
       "legendFormat": "Space"
      }
     ]
    },
    {
     "title": "application-manager-postgres-${app_mng_postgres} - Ephemeral Storage",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 107 },
     "repeat": "app_mng_postgres",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_fs_reads_bytes_total{container=\"application-manager-postgres\", namespace=\"$namespace\", pod=\"application-manager-postgres-${app_mng_postgres}\"}",
       "legendFormat": "{{device}} reads"
      },
      {
       "expr": "container_fs_writes_bytes_total{container=\"application-manager-postgres\", namespace=\"$namespace\", pod=\"application-manager-postgres-${app_mng_postgres}\"}",
       "legendFormat": "{{device}} writes"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{container=\"application-manager-postgres\", namespace=\"$namespace\", pod=\"application-manager-postgres-${app_mng_postgres}\", resource=\"ephemeral_storage\", unit=\"byte\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{container=\"application-manager-postgres\", namespace=\"$namespace\", pod=\"application-manager-postgres-${app_mng_postgres}\", resource=\"ephemeral_storage\", unit=\"byte\"})",
       "legendFormat": "Limits"
      }
     ]
    }
   ]
  },
  {
   "title": "WFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "eric-am-common-wfs (eric-am-common-wfs-${eric_am_common_wfs}) - Memory",
     "type": "graph",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 2 },
     "repeat": "eric_am_common_wfs",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{namespace=\"${namespace}\", pod=~\"eric-am-common-wfs-${eric_am_common_wfs}\", container=\"eric-am-common-wfs\", service=\"${kubelet_service}\"})",
       "legendFormat": "Working set (all touched pages)"
      },
      {
       "expr": "container_memory_rss{namespace=\"${namespace}\", pod=~\"eric-am-common-wfs-${eric_am_common_wfs}\", container=\"eric-am-common-wfs\", service=\"${kubelet_service}\"}",
       "legendFormat": "Rss (size of memory used by a container's working set)"
      },
      {
       "expr": "max(container_memory_usage_bytes{namespace=\"${namespace}\", pod=~\"eric-am-common-wfs-${eric_am_common_wfs}\", container=\"eric-am-common-wfs\", service=\"${kubelet_service}\"})",
       "legendFormat": "Usage (all memory usage)"
      },
      {
       "expr": "max(container_memory_max_usage_bytes{namespace=\"${namespace}\", pod=~\"eric-am-common-wfs-${eric_am_common_wfs}\", container=\"eric-am-common-wfs\", service=\"${kubelet_service}\"})",
       "legendFormat": "Max Usage (maximum memory usage recorded)"
      },
      {
       "expr": "max(container_memory_cache{namespace=\"${namespace}\", pod=~\"eric-am-common-wfs-${eric_am_common_wfs}\", container=\"eric-am-common-wfs\", service=\"${kubelet_service}\"})",
       "legendFormat": "Cache (container's page cache)"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"memory\", pod=~\"eric-am-common-wfs-${eric_am_common_wfs}\", container=\"eric-am-common-wfs\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"memory\", pod=~\"eric-am-common-wfs-${eric_am_common_wfs}\", container=\"eric-am-common-wfs\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "eric-am-common-wfs (eric-am-common-wfs-${eric_am_common_wfs}) - CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "repeat": "eric_am_common_wfs",
     "fieldConfig": { "defaults": { "unit": "core" } },
     "yaxes": [
      { "format": "core" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\", pod=~\"eric-am-common-wfs-${eric_am_common_wfs}\", container=\"eric-am-common-wfs\", service=\"${kubelet_service}\"}[1m]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"cpu\", pod=~\"eric-am-common-wfs-${eric_am_common_wfs}\", container=\"eric-am-common-wfs\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"cpu\", pod=~\"eric-am-common-wfs-${eric_am_common_wfs}\", container=\"eric-am-common-wfs\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "eric-am-common-wfs-${eric_am_common_wfs} - Network I/O",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "repeat": "eric_am_common_wfs",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"${namespace}\", pod=~\"eric-am-common-wfs-${eric_am_common_wfs}\", interface=\"eth0\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Received Bytes"
      },
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"${namespace}\", pod=~\"eric-am-common-wfs-${eric_am_common_wfs}\", interface=\"eth0\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Transmitted Bytes"
      }
     ]
    },
    {
     "title": "eric-am-common-wfs (eric-am-common-wfs-${eric_am_common_wfs})  - Disk IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
     "repeat": "eric_am_common_wfs",
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_reads_total{namespace=\"${namespace}\", container=\"eric-am-common-wfs\", pod=~\"eric-am-common-wfs-${eric_am_common_wfs}\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Reads {{device}}"
      },
      {
       "expr": "rate(container_fs_writes_total{namespace=\"${namespace}\", container=\"eric-am-common-wfs\", pod=~\"eric-am-common-wfs-${eric_am_common_wfs}\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Writes {{device}}"
      }
     ]
    },
    {
     "title": "eric-am-common-wfs (eric-am-common-wfs-${eric_am_common_wfs}) -  Disk Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
     "repeat": "eric_am_common_wfs",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_reads_bytes_total{namespace=\"${namespace}\", container=\"eric-am-common-wfs\", pod=~\"eric-am-common-wfs-${eric_am_common_wfs}\", service=\"${kubelet_service}\"}[$__rate_interval])",
       "legendFormat": "Reads {{device}}"
      },
      {
       "expr": "rate(container_fs_writes_bytes_total{namespace=\"${namespace}\", container=\"eric-am-common-wfs\", pod=~\"eric-am-common-wfs-${eric_am_common_wfs}\", service=\"${kubelet_service}\"}[$__rate_interval])",
       "legendFormat": "Writes {{device}}"
      }
     ]
    },
    {
     "title": "eric-am-common-wfs-${eric_am_common_wfs} - Processes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
     "repeat": "eric_am_common_wfs",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "container_processes{namespace=\"$namespace\", container=\"eric-am-common-wfs\", pod=~\"eric-am-common-wfs-${eric_am_common_wfs}\"}",
       "legendFormat": "{{container}} count"
      }
     ]
    },
    {
     "title": "eric-am-common-wfs (eric-am-common-wfs-${eric_am_common_wfs}) - Ephemeral Storage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 63 },
     "repeat": "eric_am_common_wfs",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_fs_reads_bytes_total{container=\"eric-am-common-wfs\", namespace=\"${namespace}\", pod=~\"eric-am-common-wfs-${eric_am_common_wfs}\"}",
       "legendFormat": "{{device}} reads"
      },
      {
       "expr": "container_fs_writes_bytes_total{container=\"eric-am-common-wfs\", namespace=\"$namespace\", pod=~\"eric-am-common-wfs-${eric_am_common_wfs}\"}",
       "legendFormat": "{{device}} writes"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"ephemeral_storage\", pod=~\"eric-am-common-wfs-${eric_am_common_wfs}\", container=\"eric-am-common-wfs\"})",
       "legendFormat": "Request"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"ephemeral_storage\", pod=~\"eric-am-common-wfs-${eric_am_common_wfs}\", container=\"eric-am-common-wfs\"})",
       "legendFormat": "Limits"
      }
     ]
    }
   ]
  },
  {
   "title": "WFS UI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "eric-am-common-wfs-ui (eric-am-common-wfs-ui-${eric_am_common_wfs_ui}) - Memory",
     "type": "graph",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 3 },
     "repeat": "eric_am_common_wfs_ui",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{namespace=\"${namespace}\", pod=~\"eric-am-common-wfs-ui-${eric_am_common_wfs_ui}\",container=\"eric-am-common-wfs-ui\", service=\"${kubelet_service}\"})",
       "legendFormat": "Working set (all touched pages)"
      },
      {
       "expr": "container_memory_rss{namespace=\"${namespace}\", pod=~\"eric-am-common-wfs-ui-${eric_am_common_wfs_ui}\", container=\"eric-am-common-wfs-ui\", service=\"${kubelet_service}\"}",
       "legendFormat": "Rss (size of memory used by a container's working set)"
      },
      {
       "expr": "max(container_memory_usage_bytes{namespace=\"${namespace}\", pod=~\"eric-am-common-wfs-ui-${eric_am_common_wfs_ui}\", container=\"eric-am-common-wfs-ui\", service=\"${kubelet_service}\"})",
       "legendFormat": "Usage (all memory usage)"
      },
      {
       "expr": "max(container_memory_max_usage_bytes{namespace=\"${namespace}\", pod=~\"eric-am-common-wfs-ui-${eric_am_common_wfs_ui}\", container=\"eric-am-common-wfs-ui\", service=\"${kubelet_service}\"})",
       "legendFormat": "Max Usage (maximum memory usage recorded)"
      },
      {
       "expr": "max(container_memory_cache{namespace=\"${namespace}\", pod=~\"eric-am-common-wfs-ui-${eric_am_common_wfs_ui}\", container=\"eric-am-common-wfs-ui\", service=\"${kubelet_service}\"})",
       "legendFormat": "Cache (container's page cache)"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"memory\", pod=~\"eric-am-common-wfs-ui-${eric_am_common_wfs_ui}\",container=\"eric-am-common-wfs-ui\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"memory\", pod=~\"eric-am-common-wfs-ui-${eric_am_common_wfs_ui}\",container=\"eric-am-common-wfs-ui\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "eric-am-common-wfs-ui (eric-am-common-wfs-ui-${eric_am_common_wfs_ui})  - CPU",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "repeat": "eric_am_common_wfs_ui",
     "fieldConfig": { "defaults": { "unit": "core" } },
     "yaxes": [
      { "format": "core" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\", pod=~\"eric-am-common-wfs-ui-${eric_am_common_wfs_ui}\", container=\"eric-am-common-wfs-ui\", service=\"${kubelet_service}\"}[1m]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"cpu\", pod=~\"eric-am-common-wfs-ui-${eric_am_common_wfs_ui}\", container=\"eric-am-common-wfs-ui\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"cpu\", pod=~\"eric-am-common-wfs-ui-${eric_am_common_wfs_ui}\", container=\"eric-am-common-wfs-ui\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "eric-am-common-wfs-ui-${eric_am_common_wfs_ui} - Network I/O",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
     "repeat": "eric_am_common_wfs_ui",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"${namespace}\", pod=~\"eric-am-common-wfs-ui-${eric_am_common_wfs_ui}\", interface=\"eth0\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Received Bytes"
      },
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"${namespace}\", pod=~\"eric-am-common-wfs-ui-${eric_am_common_wfs_ui}\", interface=\"eth0\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Transmitted Bytes"
      }
     ]
    },
    {
     "title": "eric-am-common-wfs-ui (eric-am-common-wfs-ui-${eric_am_common_wfs_ui})  - Disk IOPS",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
     "repeat": "eric_am_common_wfs_ui",
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_reads_total{namespace=\"${namespace}\", container=\"eric-am-common-wfs-ui\", pod=\"eric-am-common-wfs-ui-${eric_am_common_wfs_ui}\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Reads {{device}}"
      },
      {
       "expr": "rate(container_fs_writes_total{namespace=\"${namespace}\", container=\"eric-am-common-wfs-ui\", pod=~\"eric-am-common-wfs-ui-${eric_am_common_wfs_ui}\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Writes {{device}}"
      }
     ]
    },
    {
     "title": "eric-am-common-wfs-ui (eric-am-common-wfs-ui-${eric_am_common_wfs_ui}) -  Disk Throughput",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
     "repeat": "eric_am_common_wfs_ui",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_reads_bytes_total{namespace=\"${namespace}\", container=\"eric-am-common-wfs-ui\", pod=~\"eric-am-common-wfs-ui-${eric_am_common_wfs_ui}\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Reads {{device}}"
      },
      {
       "expr": "rate(container_fs_writes_bytes_total{namespace=\"${namespace}\", container=\"eric-am-common-wfs-ui\", pod=~\"eric-am-common-wfs-ui-${eric_am_common_wfs_ui}\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Writes {{device}}"
      }
     ]
    },
    {
     "title": "eric-am-common-wfs-ui-${eric_am_common_wfs_ui} - Processes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
     "repeat": "eric_am_common_wfs_ui",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "container_processes{namespace=\"$namespace\", container=\"eric-am-common-wfs-ui\", pod=~\"eric-am-common-wfs-ui-${eric_am_common_wfs_ui}\"}",
       "legendFormat": "{{container}} count"
      }
     ]
    },
    {
     "title": "eric-am-common-wfs-ui (eric-am-common-wfs-ui-${eric_am_common_wfs_ui}) - Ephemeral Storage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
     "repeat": "eric_am_common_wfs_ui",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_fs_reads_bytes_total{container=\"eric-am-common-wfs-ui\", namespace=\"${namespace}\", pod=~\"eric-am-common-wfs-ui-${eric_am_common_wfs_ui}\"}",
       "legendFormat": "{{device}} reads"
      },
      {
       "expr": "container_fs_writes_bytes_total{container=\"eric-am-common-wfs-ui\", namespace=\"${namespace}\", pod=~\"eric-am-common-wfs-ui-${eric_am_common_wfs_ui}\"}",
       "legendFormat": "{{device}} writes"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"ephemeral_storage\", pod=~\"eric-am-common-wfs-ui-${eric_am_common_wfs_ui}\", container=\"eric-am-common-wfs-ui\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"ephemeral_storage\", pod=~\"eric-am-common-wfs-ui-${eric_am_common_wfs_ui}\", container=\"eric-am-common-wfs-ui\"})",
       "legendFormat": "Limits"
      }
     ]
    }
   ]
  },
  {
   "title": "Onboarding",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "eric-am-onboarding-service (eric-am-onboarding-service-${eric_am_onboarding_service}) - Memory",
     "type": "graph",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 4 },
     "repeat": "eric_am_onboarding_service",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{namespace=\"${namespace}\", pod=~\"eric-am-onboarding-service-${eric_am_onboarding_service}\", container=\"eric-am-onboarding-service\", service=\"${kubelet_service}\"})",
       "legendFormat": "Working set (all touched pages)"
      },
      {
       "expr": "container_memory_rss{namespace=\"${namespace}\", pod=~\"eric-am-onboarding-service-${eric_am_onboarding_service}\", container=\"eric-am-onboarding-service\", service=\"${kubelet_service}\"}",
       "legendFormat": "Rss (size of memory used by a container's working set)"
      },
      {
       "expr": "max(container_memory_usage_bytes{namespace=\"${namespace}\", pod=~\"eric-am-onboarding-service-${eric_am_onboarding_service}\", container=\"eric-am-onboarding-service\", service=\"${kubelet_service}\"})",
       "legendFormat": "Usage (all memory usage)"
      },
      {
       "expr": "max(container_memory_max_usage_bytes{namespace=\"${namespace}\", pod=~\"eric-am-onboarding-service-${eric_am_onboarding_service}\", container=\"eric-am-onboarding-service\", service=\"${kubelet_service}\"})",
       "legendFormat": "Max Usage (maximum memory usage recorded)"
      },
      {
       "expr": "max(container_memory_cache{namespace=\"${namespace}\", pod=~\"eric-am-onboarding-service-${eric_am_onboarding_service}\", container=\"eric-am-onboarding-service\", service=\"${kubelet_service}\"})",
       "legendFormat": "Cache (container's page cache)"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"memory\", pod=~\"eric-am-onboarding-service-${eric_am_onboarding_service}\", container=\"eric-am-onboarding-service\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"memory\", pod=~\"eric-am-onboarding-service-${eric_am_onboarding_service}\", container=\"eric-am-onboarding-service\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "eric-am-onboarding-service (eric-am-onboarding-service-${eric_am_onboarding_service}) - CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "repeat": "eric_am_onboarding_service",
     "fieldConfig": { "defaults": { "unit": "core" } },
     "yaxes": [
      { "format": "core" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\", pod=~\"eric-am-onboarding-service-${eric_am_onboarding_service}\", container=\"eric-am-onboarding-service\", service=\"${kubelet_service}\"}[1m]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"cpu\", pod=~\"eric-am-onboarding-service-${eric_am_onboarding_service}\", container=\"eric-am-onboarding-service\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"cpu\", pod=~\"eric-am-onboarding-service-${eric_am_onboarding_service}\", container=\"eric-am-onboarding-service\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "eric-am-onboarding-service-${eric_am_onboarding_service} - Network I/O",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
     "repeat": "eric_am_onboarding_service",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"${namespace}\", pod=\"eric-am-onboarding-service-${eric_am_onboarding_service}\", interface=\"eth0\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Received Bytes"
      },
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"${namespace}\", pod=\"eric-am-onboarding-service-${eric_am_onboarding_service}\", interface=\"eth0\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Transmitted Bytes"
      }
     ]
    },
    {
     "title": "eric-am-onboarding-service (eric-am-onboarding-service-${eric_am_onboarding_service})  - Disk IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
     "repeat": "eric_am_onboarding_service",
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_reads_total{namespace=\"${namespace}\", container=\"eric-am-onboarding-service\", pod=~\"eric-am-onboarding-service-${eric_am_onboarding_service}\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Reads {{device}}"
      },
      {
       "expr": "rate(container_fs_writes_total{namespace=\"${namespace}\", container=\"eric-am-onboarding-service\", pod=~\"eric-am-onboarding-service-${eric_am_onboarding_service}\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Writes {{device}}"
      }
     ]
    },
    {
     "title": "eric-am-onboarding-service (eric-am-onboarding-service-${eric_am_onboarding_service}) -  Disk Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
     "repeat": "eric_am_onboarding_service",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_reads_bytes_total{namespace=\"${namespace}\", container=\"eric-am-onboarding-service\", pod=~\"eric-am-onboarding-service-${eric_am_onboarding_service}\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Reads {{device}}"
      },
      {
       "expr": "rate(container_fs_writes_bytes_total{namespace=\"${namespace}\", container=\"eric-am-onboarding-service\", pod=~\"eric-am-onboarding-service-${eric_am_onboarding_service}\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Writes {{device}}"
      }
     ]
    },
    {
     "title": "eric-am-onboarding-service-${eric_am_onboarding_service} - Processes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
     "repeat": "eric_am_onboarding_service",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "container_processes{namespace=\"$namespace\", container=\"eric-am-onboarding-service\", pod=~\"eric-am-onboarding-service-${eric_am_onboarding_service}\"}",
       "legendFormat": "{{container}} count"
      }
     ]
    },
    {
     "title": "eric-am-onboarding-service (eric-am-onboarding-service-${eric_am_onboarding_service}) - Ephemeral Storage",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 67 },
     "repeat": "eric_am_onboarding_service",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_fs_reads_bytes_total{container=\"eric-am-onboarding-service\", namespace=\"${namespace}\", pod=~\"eric-am-onboarding-service-${eric_am_onboarding_service}\"}",
       "legendFormat": "{{device}} reads"
      },
      {
       "expr": "container_fs_writes_bytes_total{container=\"eric-am-onboarding-service\", namespace=\"${namespace}\", pod=~\"eric-am-onboarding-service-${eric_am_onboarding_service}\"}",
       "legendFormat": "{{device}} writes"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"ephemeral_storage\", pod=~\"eric-am-onboarding-service-${eric_am_onboarding_service}\", container=\"eric-am-onboarding-service\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"ephemeral_storage\", pod=~\"eric-am-onboarding-service-${eric_am_onboarding_service}\", container=\"eric-am-onboarding-service\"})",
       "legendFormat": "Limits"
      }
     ]
    }
   ]
  },
  {
   "title": "Crypto",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "eric-eo-evnfm-crypto (eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}) - Memory",
     "type": "graph",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 5 },
     "repeat": "eric_eo_evnfm_crypto",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{namespace=\"${namespace}\", container=\"eric-eo-evnfm-crypto\", pod=~\"eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}\", service=\"${kubelet_service}\"})",
       "legendFormat": "Working set (all touched pages)"
      },
      {
       "expr": "container_memory_rss{namespace=\"${namespace}\", pod=~\"eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}\", container=\"eric-eo-evnfm-crypto\", service=\"${kubelet_service}\"}",
       "legendFormat": "Rss (size of memory used by a container's working set)"
      },
      {
       "expr": "max(container_memory_usage_bytes{namespace=\"${namespace}\", pod=~\"eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}\", container=\"eric-eo-evnfm-crypto\", service=\"${kubelet_service}\"})",
       "legendFormat": "Usage (all memory usage)"
      },
      {
       "expr": "max(container_memory_max_usage_bytes{namespace=\"${namespace}\", pod=~\"eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}\", container=\"eric-eo-evnfm-crypto\", service=\"${kubelet_service}\"})",
       "legendFormat": "Max Usage (maximum memory usage recorded)"
      },
      {
       "expr": "max(container_memory_cache{namespace=\"${namespace}\", pod=~\"eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}\", container=\"eric-eo-evnfm-crypto\", service=\"${kubelet_service}\"})",
       "legendFormat": "Cache (container's page cache)"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"memory\", container=\"eric-eo-evnfm-crypto\", pod=~\"eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\",  resource=\"memory\", container=\"eric-eo-evnfm-crypto\", pod=~\"eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "eric-eo-evnfm-crypto (eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}) - CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "repeat": "eric_eo_evnfm_crypto",
     "fieldConfig": { "defaults": { "unit": "core" } },
     "yaxes": [
      { "format": "core" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\", container=\"eric-eo-evnfm-crypto\", pod=\"eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}\", service=\"${kubelet_service}\"}[1m]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"cpu\", container=\"eric-eo-evnfm-crypto\", pod=\"eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"cpu\", container=\"eric-eo-evnfm-crypto\", pod=\"eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto} - Network I/O",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "repeat": "eric_eo_evnfm_crypto",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"${namespace}\", pod=\"eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}\", interface=\"eth0\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Received Bytes"
      },
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"${namespace}\", pod=\"eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}\", interface=\"eth0\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Transmitted Bytes"
      }
     ]
    },
    {
     "title": "eric-eo-evnfm-crypto (eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}) - Disk IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
     "repeat": "eric_eo_evnfm_crypto",
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "(rate(container_fs_reads_total{namespace=\"${namespace}\", container=\"eric-eo-evnfm-crypto\", pod=~\"eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}\", service=\"${kubelet_service}\"}[1m]))",
       "legendFormat": "Reads {{device}}"
      },
      {
       "expr": "(rate(container_fs_writes_total{namespace=\"${namespace}\", container=\"eric-eo-evnfm-crypto\", pod=~\"eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}\", service=\"${kubelet_service}\"}[1m]))",
       "legendFormat": "Writes {{device}}"
      }
     ]
    },
    {
     "title": "eric-eo-evnfm-crypto (eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}) -  Disk Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
     "repeat": "eric_eo_evnfm_crypto",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max by (device) (rate(container_fs_reads_bytes_total{namespace=\"${namespace}\", container=\"eric-eo-evnfm-crypto\", pod=~\"eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}\", service=\"${kubelet_service}\"}[$__rate_interval]))",
       "legendFormat": "Reads {{device}}"
      },
      {
       "expr": "max by (device) (rate(container_fs_writes_bytes_total{namespace=\"${namespace}\", container=\"eric-eo-evnfm-crypto\", pod=~\"eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}\", service=\"${kubelet_service}\"}[$__rate_interval]))",
       "legendFormat": "Writes {{device}}"
      }
     ]
    },
    {
     "title": "eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto} - Processes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
     "repeat": "eric_eo_evnfm_crypto",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "container_processes{namespace=\"$namespace\", container=\"eric-eo-evnfm-crypto\", pod=~\"eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}\"}",
       "legendFormat": "{{container}} count"
      }
     ]
    },
    {
     "title": "eric-eo-evnfm-crypto (eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}) - Ephemeral Storage",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 66 },
     "repeat": "eric_eo_evnfm_crypto",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_fs_reads_bytes_total{container=\"eric-eo-evnfm-crypto\", namespace=\"${namespace}\", pod=~\"eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}\"}",
       "legendFormat": "{{device}} reads"
      },
      {
       "expr": "container_fs_writes_bytes_total{container=\"eric-eo-evnfm-crypto\", namespace=\"${namespace}\", pod=~\"eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}\"}",
       "legendFormat": "{{device}} writes"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"ephemeral_storage\", pod=~\"eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}\", container=\"eric-eo-evnfm-crypto\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"ephemeral_storage\", pod=~\"eric-eo-evnfm-crypto-${eric_eo_evnfm_crypto}\", container=\"eric-eo-evnfm-crypto\"})",
       "legendFormat": "Limits"
      }
     ]
    }
   ]
  },
  {
   "title": "NBI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "eric-eo-evnfm-nbi (eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}) - Memory",
     "type": "graph",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 6 },
     "repeat": "eric_eo_evnfm_nbi",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{namespace=\"${namespace}\", pod=~\"eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}\", container=\"eric-eo-evnfm-nbi\", service=\"${kubelet_service}\"})",
       "legendFormat": "Working set (all touched pages)"
      },
      {
       "expr": "container_memory_rss{namespace=\"${namespace}\", pod=~\"eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}\", container=\"eric-eo-evnfm-nbi\", service=\"${kubelet_service}\"}",
       "legendFormat": "Rss (size of memory used by a container's working set)"
      },
      {
       "expr": "max(container_memory_usage_bytes{namespace=\"${namespace}\", pod=~\"eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}\", container=\"eric-eo-evnfm-nbi\", service=\"${kubelet_service}\"})",
       "legendFormat": "Usage (all memory usage)"
      },
      {
       "expr": "max(container_memory_max_usage_bytes{namespace=\"${namespace}\", pod=~\"eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}\", container=\"eric-eo-evnfm-nbi\", service=\"${kubelet_service}\"})",
       "legendFormat": "Max Usage (maximum memory usage recorded)"
      },
      {
       "expr": "max(container_memory_cache{namespace=\"${namespace}\", pod=~\"eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}\", container=\"eric-eo-evnfm-nbi\", service=\"${kubelet_service}\"})",
       "legendFormat": "Cache (container's page cache)"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"memory\", pod=~\"eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}\", container=\"eric-eo-evnfm-nbi\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"memory\", pod=~\"eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}\", container=\"eric-eo-evnfm-nbi\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "eric-eo-evnfm-nbi (eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}) - CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "repeat": "eric_eo_evnfm_nbi",
     "fieldConfig": { "defaults": { "unit": "core" } },
     "yaxes": [
      { "format": "core" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\", pod=~\"eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}\", container=\"eric-eo-evnfm-nbi\", service=\"${kubelet_service}\"}[1m]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"cpu\", pod=~\"eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}\", container=\"eric-eo-evnfm-nbi\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"cpu\", pod=~\"eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}\", container=\"eric-eo-evnfm-nbi\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi} - Network I/O",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "repeat": "eric_eo_evnfm_nbi",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"${namespace}\", pod=~\"eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}\", interface=\"eth0\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Received Bytes"
      },
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"${namespace}\", pod=~\"eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}\", interface=\"eth0\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Transmitted Bytes"
      }
     ]
    },
    {
     "title": "eric-eo-evnfm-nbi (eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}) - Disk IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
     "repeat": "eric_eo_evnfm_nbi",
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_reads_total{namespace=\"${namespace}\", container=\"eric-eo-evnfm-nbi\", pod=~\"eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Reads {{device}}"
      },
      {
       "expr": "rate(container_fs_writes_total{namespace=\"${namespace}\", container=\"eric-eo-evnfm-nbi\", pod=~\"eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Writes {{device}}"
      }
     ]
    },
    {
     "title": "eric-eo-evnfm-nbi (eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}) -  Disk Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
     "repeat": "eric_eo_evnfm_nbi",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_reads_bytes_total{namespace=\"${namespace}\", container=\"eric-eo-evnfm-nbi\", pod=~\"eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Reads {{device}}"
      },
      {
       "expr": "rate(container_fs_writes_bytes_total{namespace=\"${namespace}\", container=\"eric-eo-evnfm-nbi\", pod=~\"eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Writes {{device}}"
      }
     ]
    },
    {
     "title": "eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi} - Processes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
     "repeat": "eric_eo_evnfm_nbi",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "container_processes{namespace=\"$namespace\", container=\"eric-eo-evnfm-nbi\", pod=~\"eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}\"}",
       "legendFormat": "{{container}} count"
      }
     ]
    },
    {
     "title": "eric-eo-evnfm-nbi (eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}) - Ephemeral Storage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 68 },
     "repeat": "eric_eo_evnfm_nbi",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_fs_reads_bytes_total{container=\"eric-eo-evnfm-nbi\", namespace=\"$namespace\", pod=\"eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}\"}",
       "legendFormat": "{{device}} reads"
      },
      {
       "expr": "container_fs_writes_bytes_total{container=\"eric-eo-evnfm-nbi\", namespace=\"$namespace\", pod=\"eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}\"}",
       "legendFormat": "{{device}} writes"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"ephemeral_storage\", pod=~\"eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}\", container=\"eric-eo-evnfm-nbi\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"ephemeral_storage\", pod=~\"eric-eo-evnfm-nbi-${eric_eo_evnfm_nbi}\", container=\"eric-eo-evnfm-nbi\"})",
       "legendFormat": "Limits"
      }
     ]
    }
   ]
  },
  {
   "title": "Orchestrator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "eric-vnfm-orchestrator-service (eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}) - Memory",
     "type": "graph",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 7 },
     "repeat": "eric_vnfm_orchestrator_service",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{namespace=\"${namespace}\", pod=\"eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}\", container=\"eric-vnfm-orchestrator-service\", service=\"${kubelet_service}\"})",
       "legendFormat": "Working set (all touched pages)"
      },
      {
       "expr": "container_memory_rss{namespace=\"${namespace}\", pod=~\"eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}\", container=\"eric-vnfm-orchestrator-service\", service=\"${kubelet_service}\"}",
       "legendFormat": "Rss (size of memory used by a container's working set)"
      },
      {
       "expr": "max(container_memory_usage_bytes{namespace=\"${namespace}\", pod=~\"eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}\", container=\"eric-vnfm-orchestrator-service\", service=\"${kubelet_service}\"})",
       "legendFormat": "Usage (all memory usage)"
      },
      {
       "expr": "max(container_memory_max_usage_bytes{namespace=\"${namespace}\", pod=~\"eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}\", container=\"eric-vnfm-orchestrator-service\", service=\"${kubelet_service}\"})",
       "legendFormat": "Max Usage (maximum memory usage recorded)"
      },
      {
       "expr": "max(container_memory_cache{namespace=\"${namespace}\", pod=~\"eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}\", container=\"eric-vnfm-orchestrator-service\", service=\"${kubelet_service}\"})",
       "legendFormat": "Cache (container's page cache)"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"memory\", pod=\"eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}\", container=\"eric-vnfm-orchestrator-service\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"memory\", pod=\"eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}\", container=\"eric-vnfm-orchestrator-service\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "eric-vnfm-orchestrator-service (eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}) - CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
     "repeat": "eric_vnfm_orchestrator_service",
     "fieldConfig": { "defaults": { "unit": "core" } },
     "yaxes": [
      { "format": "core" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\", pod=~\"eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}\", container=\"eric-vnfm-orchestrator-service\", service=\"${kubelet_service}\"}[1m]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"cpu\", pod=~\"eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}\", container=\"eric-vnfm-orchestrator-service\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"cpu\", pod=~\"eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}\", container=\"eric-vnfm-orchestrator-service\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service} - Network I/O",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
     "repeat": "eric_vnfm_orchestrator_service",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"${namespace}\", pod=~\"eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}\", interface=\"eth0\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Received Bytes"
      },
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"${namespace}\", pod=~\"eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}\", interface=\"eth0\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Transmitted Bytes"
      }
     ]
    },
    {
     "title": "eric-vnfm-orchestrator-service (eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service})  - Disk IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
     "repeat": "eric_vnfm_orchestrator_service",
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_reads_total{namespace=\"${namespace}\", pod=\"eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}\", container=\"eric-vnfm-orchestrator-service\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Reads {{device}}"
      },
      {
       "expr": "rate(container_fs_writes_total{namespace=\"${namespace}\", pod=\"eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}\", container=\"eric-vnfm-orchestrator-service\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Writes {{device}}"
      }
     ]
    },
    {
     "title": "eric-vnfm-orchestrator-service (eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}) -  Disk Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
     "repeat": "eric_vnfm_orchestrator_service",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_reads_bytes_total{namespace=\"${namespace}\", pod=\"eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}\", container=\"eric-vnfm-orchestrator-service\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Reads {{device}}"
      },
      {
       "expr": "rate(container_fs_writes_bytes_total{namespace=\"${namespace}\", pod=\"eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}\", container=\"eric-vnfm-orchestrator-service\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Writes {{device}}"
      }
     ]
    },
    {
     "title": "eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service} - Processes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
     "repeat": "eric_vnfm_orchestrator_service",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "container_processes{namespace=\"$namespace\", container=\"eric-vnfm-orchestrator-service\", pod=~\"eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}\"}",
       "legendFormat": "{{container}} count"
      }
     ]
    },
    {
     "title": "eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service} - Ephemeral Storage",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 69 },
     "repeat": "eric_vnfm_orchestrator_service",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_fs_reads_bytes_total{container=\"eric-vnfm-orchestrator-service\", namespace=\"${namespace}\", pod=~\"eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}\"}",
       "legendFormat": "{{device}} reads"
      },
      {
       "expr": "container_fs_writes_bytes_total{container=\"eric-vnfm-orchestrator-service\", namespace=\"${namespace}\", pod=~\"eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}\"}",
       "legendFormat": "{{device}} writes"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"ephemeral_storage\", pod=~\"eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}\", container=\"eric-vnfm-orchestrator-service\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"ephemeral_storage\", pod=~\"eric-vnfm-orchestrator-service-${eric_vnfm_orchestrator_service}\", container=\"eric-vnfm-orchestrator-service\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "eric-vnfm-orchestrator-service (${eric_vnfm_ip_orchestrator_service}) - SSH connections to ENM",
     "type": "timeseries",
     "description": "This metric shows the number of open connections to the ENM for a time interval",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
     "repeat": "eric_vnfm_ip_orchestrator_service",
     "targets": [
      {
       "expr": "round(increase(cvnfm_enm_running_metrics_total{instance=~\"${eric_vnfm_ip_orchestrator_service}\", kubernetes_namespace=\"${namespace}\", enm_metric_name=\"open_ssh_to_enm\"}[1m]))",
       "legendFormat": "connections/1m"
      },
      {
       "expr": "increase(cvnfm_enm_running_metrics_total{instance=~\"${eric_vnfm_ip_orchestrator_service}\", kubernetes_namespace=\"${namespace}\",enm_metric_name=\"open_ssh_to_enm\"}[1m]) - ignoring(enm_metric_name) increase(cvnfm_enm_running_metrics_total{instance=~\"${eric_vnfm_ip_orchestrator_service}\", kubernetes_namespace=\"${namespace}\",enm_metric_name=\"close_ssh_to_enm\"}[1m])",
       "legendFormat": "unclosed/1m"
      }
     ]
    },
    {
     "title": "eric-vnfm-orchestrator-service (${eric_vnfm_ip_orchestrator_service}) - AddNode operations",
     "type": "timeseries",
     "description": "This metric shows the number of addNode operations per time interval.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
     "repeat": "eric_vnfm_ip_orchestrator_service",
     "targets": [
      {
       "expr": "round(increase(cvnfm_enm_running_metrics_total{instance=~\"${eric_vnfm_ip_orchestrator_service}\", kubernetes_namespace=\"${namespace}\",enm_metric_name=\"started_add_node_operations\"}[1m]))",
       "legendFormat": "addNode/1m"
      },
      {
       "expr": "cvnfm_enm_running_metrics_total{instance=~\"${eric_vnfm_ip_orchestrator_service}\", kubernetes_namespace=\"${namespace}\",enm_metric_name=\"started_add_node_operations\"} - ignoring(enm_metric_name) cvnfm_enm_running_metrics_total{instance=~\"${eric_vnfm_ip_orchestrator_service}\", kubernetes_namespace=\"${namespace}\",enm_metric_name=\"completed_add_node_operations\"}",
       "legendFormat": "unfinished/1m"
      }
     ]
    },
    {
     "title": "eric-vnfm-orchestrator-service (${eric_vnfm_ip_orchestrator_service}) - Instantiate with addNode ",
     "type": "timeseries",
     "description": "This metric shows the number of addNode operations per time interval.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 97 },
     "repeat": "eric_vnfm_ip_orchestrator_service",
     "targets": [
      {
       "expr": "round(increase(cvnfm_enm_running_metrics_total{instance=~\"${eric_vnfm_ip_orchestrator_service}\", kubernetes_namespace=\"${namespace}\",enm_metric_name=\"instantiate_add_node_to_oss\"}[1m]))",
       "legendFormat": "instantiate/1m"
      }
     ]
    },
    {
     "title": "eric-vnfm-orchestrator-service (${eric_vnfm_ip_orchestrator_service}) - Instantiate with enrollment",
     "type": "timeseries",
     "description": "This metric shows the number of addNode operations per time interval.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 105 },
     "repeat": "eric_vnfm_ip_orchestrator_service",
     "targets": [
      {
       "expr": "round(increase(cvnfm_enm_running_metrics_total{instance=~\"${eric_vnfm_ip_orchestrator_service}\", kubernetes_namespace=\"${namespace}\",enm_metric_name=\"instantiate_enrollment\"}[1m]))",
       "legendFormat": "instantiate/1m"
      }
     ]
    }
   ]
  },
  {
   "title": "Batch Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "eric-eo-batch-manager (eric-eo-batch-manager-${eric_eo_batch_manager}) - Memory",
     "type": "graph",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 8 },
     "repeat": "eric_eo_batch_manager",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{namespace=\"${namespace}\", pod=\"eric-eo-batch-manager-${eric_eo_batch_manager}\", container=\"eric-eo-batch-manager\", service=\"${kubelet_service}\"})",
       "legendFormat": "Working set (all touched pages)"
      },
      {
       "expr": "container_memory_rss{namespace=\"${namespace}\", pod=~\"eric-eo-batch-manager-${eric_eo_batch_manager}\", container=\"eric-eo-batch-manager\", service=\"${kubelet_service}\"}",
       "legendFormat": "Rss (size of memory used by a container's working set)"
      },
      {
       "expr": "max(container_memory_usage_bytes{namespace=\"${namespace}\", pod=~\"eric-eo-batch-manager-${eric_eo_batch_manager}\", container=\"eric-eo-batch-manager\", service=\"${kubelet_service}\"})",
       "legendFormat": "Usage (all memory usage)"
      },
      {
       "expr": "max(container_memory_max_usage_bytes{namespace=\"${namespace}\", pod=~\"eric-eo-batch-manager-${eric_eo_batch_manager}\", container=\"eric-eo-batch-manager\", service=\"${kubelet_service}\"})",
       "legendFormat": "Max Usage (maximum memory usage recorded)"
      },
      {
       "expr": "max(container_memory_cache{namespace=\"${namespace}\", pod=~\"eric-eo-batch-manager-${eric_eo_batch_manager}\", container=\"eric-eo-batch-manager\", service=\"${kubelet_service}\"})",
       "legendFormat": "Cache (container's page cache)"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"memory\", pod=\"eric-eo-batch-manager-${eric_eo_batch_manager}\", container=\"eric-eo-batch-manager\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"memory\", pod=\"eric-eo-batch-manager-${eric_eo_batch_manager}\", container=\"eric-eo-batch-manager\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "eric-eo-batch-manager (eric-eo-batch-manager-${eric_eo_batch_manager}) - CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
     "repeat": "eric_eo_batch_manager",
     "fieldConfig": { "defaults": { "unit": "core" } },
     "yaxes": [
      { "format": "core" }
     ],
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"${namespace}\", pod=~\"eric-eo-batch-manager-${eric_eo_batch_manager}\", container=\"eric-eo-batch-manager\", service=\"${kubelet_service}\"}[1m]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"cpu\", pod=~\"eric-eo-batch-manager-${eric_eo_batch_manager}\", container=\"eric-eo-batch-manager\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"cpu\", pod=~\"eric-eo-batch-manager-${eric_eo_batch_manager}\", container=\"eric-eo-batch-manager\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "eric-eo-batch-manager-${eric_eo_batch_manager} - Network I/O",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
     "repeat": "eric_eo_batch_manager",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"${namespace}\", pod=~\"eric-eo-batch-manager-${eric_eo_batch_manager}\", interface=\"eth0\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Received Bytes"
      },
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"${namespace}\", pod=~\"eric-eo-batch-manager-${eric_eo_batch_manager}\", interface=\"eth0\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Transmitted Bytes"
      }
     ]
    },
    {
     "title": "eric-eo-batch-manager (eric-eo-batch-manager-${eric_eo_batch_manager})  - Disk IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
     "repeat": "eric_eo_batch_manager",
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_reads_total{namespace=\"${namespace}\", pod=\"eric-eo-batch-manager-${eric_eo_batch_manager}\", container=\"eric-eo-batch-manager\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Reads {{device}}"
      },
      {
       "expr": "rate(container_fs_writes_total{namespace=\"${namespace}\", pod=\"eric-eo-batch-manager-${eric_eo_batch_manager}\", container=\"eric-eo-batch-manager\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Writes {{device}}"
      }
     ]
    },
    {
     "title": "eric-eo-batch-manager (eric-eo-batch-manager-${eric_eo_batch_manager}) -  Disk Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
     "repeat": "eric_eo_batch_manager",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_reads_bytes_total{namespace=\"${namespace}\", pod=\"eric-eo-batch-manager-${eric_eo_batch_manager}\", container=\"eric-eo-batch-manager\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Reads {{device}}"
      },
      {
       "expr": "rate(container_fs_writes_bytes_total{namespace=\"${namespace}\", pod=\"eric-eo-batch-manager-${eric_eo_batch_manager}\", container=\"eric-eo-batch-manager\", service=\"${kubelet_service}\"}[1m])",
       "legendFormat": "Writes {{device}}"
      }
     ]
    },
    {
     "title": "eric-eo-batch-manager-${eric_eo_batch_manager} - Processes",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 61 },
     "repeat": "eric_eo_batch_manager",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "container_processes{namespace=\"$namespace\", container=\"eric-eo-batch-manager\", pod=~\"eric-eo-batch-manager-${eric_eo_batch_manager}\"}",
       "legendFormat": "{{container}} count"
      }
     ]
    },
    {
     "title": "eric-eo-batch-manager-${eric_eo_batch_manager} - Ephemeral Storage",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 72 },
     "repeat": "eric_eo_batch_manager",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_fs_reads_bytes_total{container=\"eric-eo-batch-manager\", namespace=\"${namespace}\", pod=~\"eric-eo-batch-manager-${eric_eo_batch_manager}\"}",
       "legendFormat": "{{device}} reads"
      },
      {
       "expr": "container_fs_writes_bytes_total{container=\"eric-eo-batch-manager\", namespace=\"${namespace}\", pod=~\"eric-eo-batch-manager-${eric_eo_batch_manager}\"}",
       "legendFormat": "{{device}} writes"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=\"${namespace}\", resource=\"ephemeral_storage\", pod=~\"eric-eo-batch-manager-${eric_eo_batch_manager}\", container=\"eric-eo-batch-manager\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=\"${namespace}\", resource=\"ephemeral_storage\", pod=~\"eric-eo-batch-manager-${eric_eo_batch_manager}\", container=\"eric-eo-batch-manager\"})",
       "legendFormat": "Limits"
      }
     ]
    }
   ]
  }
 ]
}