{
 "title": "EO Pod Startup Times",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "am_postgres_pod_name",
    "query": "application-manager-postgres-[0-9]*"
   },
   {
    "name": "am_common_wfs_pod_name",
    "query": "eric-am-common-wfs-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "am_common_wfs_ui_pod_name",
    "query": "eric-am-common-wfs-ui-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "am_onboarding_pod_name",
    "query": "eric-am-onboarding-service-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "eo_evnfm_crypto_pod_name",
    "query": "eric-eo-evnfm-crypto-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "eo_evnfm_nbi_pod_name",
    "query": "eric-eo-evnfm-nbi-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "vnfm_orchestrator_pod_name",
    "query": "eric-vnfm-orchestrator-service-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "am_postres_bra_pod_name",
    "query": "application-manager-postgres-bragent-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "gui_aggregator_pod_name",
    "query": "eric-adp-gui-aggregator-service-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "cn_kvdb_redis_pod_name",
    "query": "eric-data-key-value-database-rd-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "cm_mediator_pod_name",
    "query": "eric-cm-mediator-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "cm_mediator_notifier_pod_name",
    "query": "eric-cm-mediator-notifier-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   { "name": "cm_mediator_db_pod_name", "query": "eric-cm-mediator-db-pg-[0-9]*" },
   {
    "name": "cnom_server_pod_name",
    "query": "eric-cnom-server-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   { "name": "ctrl_bro_pod_name", "query": "eric-ctrl-bro-[0-9]*" },
   {
    "name": "data_dced_pod_name",
    "query": "eric-data-distributed-coordinator-ed-[0-9]*"
   },
   {
    "name": "data_dced_agent_pod_name",
    "query": "eric-data-distributed-coordinator-ed-agent-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "data_search_engine_pod_name",
    "query": "eric-data-search-engine-data-[0-9]*"
   },
   {
    "name": "cn_kvdb_redis_operand_pod_name",
    "query": "eric-cloud-native-kvdb-rd-operand-[a-zA-Z0-9]*"
   },
   {
    "name": "data_search_engine_ingest_pod_name",
    "query": "eric-data-search-engine-ingest-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "data_search_engine_master_pod_name",
    "query": "eric-data-search-engine-master-[0-9]*"
   },
   {
    "name": "container_registry_pod_name",
    "query": "eric-lcm-container-registry-registry-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "fh_alarm_handler_db_pod_name",
    "query": "eric-fh-alarm-handler-db-pg-[0-9]*"
   },
   {
    "name": "fh_snmp_alarm_provider_pod_name",
    "query": "eric-fh-snmp-alarm-provider-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   { "name": "log_shipper_pod_name", "query": "eric-log-shipper-[a-zA-Z0-9]*" },
   {
    "name": "log_transformer_pod_name",
    "query": "eric-log-transformer-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "helm_chart_registry_pod_name",
    "query": "eric-lcm-helm-chart-registry-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "pm_kube_state_metrics_pod_name",
    "query": "eric-pm-kube-state-metrics-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   { "name": "pm_server_pod_name", "query": "eric-pm-server-[0-9]*" },
   { "name": "sec_access_mgmt_pod_name", "query": "eric-sec-access-mgmt-[0-9]*" },
   {
    "name": "sec_certm_pod_name",
    "query": "eric-sec-certm-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "key_mgmt_pod_name",
    "query": "eric-sec-key-management-main-[0-9]*"
   },
   {
    "name": "sip_tls_pod_name",
    "query": "eric-sec-sip-tls-main-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "mesh_controller_pod_name",
    "query": "eric-mesh-controller-a-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "service_mesh_gw_pod_name",
    "query": "service-mesh-ingress-gateway-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   { "name": "pm_alert_manager_pod_name", "query": "eric-pm-alert-manager-[0-9]*" },
   { "name": "idam_db_pg_pod_name", "query": "idam-database-pg-[0-9]*" },
   {
    "name": "object_storage_mn_mgt_pod_name",
    "query": "eric-data-object-storage-mn-mgt-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "object_storage_mn_pod_name",
    "query": "eric-data-object-storage-mn-[0-9]*"
   },
   {
    "name": "fh_event_to_alarm_adapter_pod_name",
    "query": "eric-eo-fh-event-to-alarm-adapter-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "eo_api_gateway_pod_name",
    "query": "eric-eo-api-gateway-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "eo_common_br_agent_pod_name",
    "query": "eric-eo-common-br-agent-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "eo_lm_consumer_pod_name",
    "query": "eric-eo-lm-consumer-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "lm_combined_server_db_pod_name",
    "query": "eric-lm-combined-server-db-pg-[0-9]*"
   },
   {
    "name": "lm_combined_server_client_pod_name",
    "query": "eric-lm-combined-server-license-server-client-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "oss_common_postgres_pod_name",
    "query": "eric-oss-common-postgres-[0-9]*"
   },
   {
    "name": "oss_common_bragent_pod_name",
    "query": "eric-oss-common-postgres-bragent-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "evnfm_toscao_pod_name",
    "query": "evnfm-toscao-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "eo_usermgmt_pod_name",
    "query": "eric-eo-usermgmt-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "eo_usermgmt_ui_pod_name",
    "query": "eric-eo-usermgmt-ui-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   },
   {
    "name": "lm_combined_server_license_consumer_handler_pod_name",
    "query": "eric-lm-combined-server-license-consumer-handler-[a-zA-Z0-9]*"
   },
   {
    "name": "idam_db_bra_pod_name",
    "query": "idam-database-pg-bragent-[a-zA-Z0-9]*-[a-zA-Z0-9]*"
   }
  ]
 },
 "panels": [
  {
   "title": "TOSCA-O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "evnfm-toscao",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${evnfm_toscao_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${evnfm_toscao_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OSS Common DB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "oss-common-postgres-db",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${oss_common_postgres_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${oss_common_postgres_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "User Management",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "eo-user-management",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${eo_usermgmt_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${eo_usermgmt_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "eo-user-management-ui",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${eo_usermgmt_ui_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${eo_usermgmt_ui_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Licensing services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "eo-lm-consumer",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${eo_lm_consumer_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${eo_lm_consumer_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "lm-combined-server-db-pg",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${lm_combined_server_db_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${lm_combined_server_db_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "lm-combined-server-license-server-client",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${lm_combined_server_client_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${lm_combined_server_client_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "lm-combined-server-license-consumer-handler",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${lm_combined_server_license_consumer_handler_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${lm_combined_server_license_consumer_handler_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "eo-api-gateway",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${eo_api_gateway_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${eo_api_gateway_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Object Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "data-object-storage-mn-mgt",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${object_storage_mn_mgt_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${object_storage_mn_mgt_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "data-object-storage-mn",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${object_storage_mn_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${object_storage_mn_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Helm Chart/Container Registry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "lcm-helm-chart-registry",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${helm_chart_registry_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${helm_chart_registry_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "lcm-container-registry",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${container_registry_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${container_registry_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CM Mediator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "configuration-management-mediator",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${cm_mediator_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${cm_mediator_pod_name}\"})",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${cm_mediator_notifier_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${cm_mediator_notifier_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "configuration-management-mediator-db-postgres",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${cm_mediator_db_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${cm_mediator_db_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alarm Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "fh-snmp-alarm-provider",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${fh_snmp_alarm_provider_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${fh_snmp_alarm_provider_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "fh-alarm-handler-database-postgres",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${fh_alarm_handler_db_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${fh_alarm_handler_db_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "fh-event-to-alarm-adapter",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${fh_event_to_alarm_adapter_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${fh_event_to_alarm_adapter_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CNOM Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "cnom-server",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${cnom_server_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${cnom_server_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Distributed Coordinator ED",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "data-distributed-coordinator-ed",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${data_dced_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${data_dced_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "data-distributed-coordinator-ed-agent",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${data_dced_agent_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${data_dced_agent_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Mesh",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "mesh-controller",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${mesh_controller_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${mesh_controller_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "service-mesh-ingress-gateway",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${service_mesh_gw_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${service_mesh_gw_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PM Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "pm-kube-state-metrics",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${pm_kube_state_metrics_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${pm_kube_state_metrics_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "pm-server",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${pm_server_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${pm_server_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "pm-alert-manager",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${pm_alert_manager_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${pm_alert_manager_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logging Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "log-transformer",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${log_transformer_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${log_transformer_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "log-shipper",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${log_shipper_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${log_shipper_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "KVDB Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "cloud-native-kvdb-redis",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${cn_kvdb_redis_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${cn_kvdb_redis_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "cloud-native-kvdb-redis-operand",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${cn_kvdb_redis_operand_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${cn_kvdb_redis_operand_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GUI Aggregator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "adp-gui-aggregator-service",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${gui_aggregator_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${gui_aggregator_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Search Engine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "data-search-engine-data",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${data_search_engine_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${data_search_engine_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "data-search-engine-master",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${data_search_engine_master_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${data_search_engine_master_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "data-search-engine-ingest",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${data_search_engine_ingest_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${data_search_engine_ingest_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backup Restore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "backup-restore-orchestrator",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${ctrl_bro_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${ctrl_bro_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "oss-common-postgres-bragent",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${oss_common_bragent_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${oss_common_bragent_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "eo-common-br-agent",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${eo_common_br_agent_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${eo_common_br_agent_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "application-manager-postgres-bra",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${am_postres_bra_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${am_postres_bra_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "idam-database-postgres-bra",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${idam_db_bra_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${idam_db_bra_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Security Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "security-certificate-management",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${sec_certm_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${sec_certm_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "security-identity-provider-tls",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${sip_tls_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${sip_tls_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "security-key-management",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${key_mgmt_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${key_mgmt_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "security-access-management",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${sec_access_mgmt_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${sec_access_mgmt_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "idam-database-postgres",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${idam_db_pg_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${idam_db_pg_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CVNFM Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "apllication-manager-postgres",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${am_postgres_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${am_postgres_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "am-onboarding-service",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${am_onboarding_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${am_onboarding_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "eo-evnfm-crypto",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${eo_evnfm_crypto_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${eo_evnfm_crypto_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "vnfm-orchestrator",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${vnfm_orchestrator_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${vnfm_orchestrator_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "am-common-wfs",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${am_common_wfs_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${am_common_wfs_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "am-common-wfs-ui",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${am_common_wfs_ui_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${am_common_wfs_ui_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "eo-evnfm-nbi",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kube_pod_status_ready_time{namespace=\"${namespace}\",pod=~\"${eo_evnfm_nbi_pod_name}\"}) - (kube_pod_status_scheduled_time{namespace=\"${namespace}\",pod=~\"${eo_evnfm_nbi_pod_name}\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}